### ISSUE TITLE
sh3_arc::LoadFile( ) seeming reads nothing

### ISSUE THREAD

**Issue by Quaker762** [Palm-Studios/sh3redux#43]
Printing out the buffer in it's entirety with 

`    for(int i = 0; i < 2048; i++)
     std::printf("0x%x ", buffer[i]);`

on Line 190-191 in types.cpp results in only 0s being printed.  This is the case when passing a vector reference to it in texture as well. 

Also, how would I copy values from the read `std::vector` into a struct? Google isn't really giving me any answers.

**Comment by z33ky** [comment]
Could be an off-by-one wrt the index. I do get a 0xffffffff if I use `(index - 1) * sizeof(fileEntry)` instead of `index * sizeof(fileEntry)` when seeking into the file in `sh3_arc::LoadFile`.

**Comment by z33ky** [comment]
> Also, how would I copy values from the read std::vector into a struct?

Completely missed that one. There should be an API like `sh3_arc_file` for this.

**Comment by Quaker762** [comment]
Okay, gotcha. So the caller can't just copy a section of the vector into struc? (sorry, I'm so used to C file handling/buffers haha)

**Comment by z33ky** [comment]
It's possible, just `std::copy(begin(vector), end(vector), reinterpret_cast<char*>(&struct));`, but why go through the vector when you can load the data directly to the struct?

**Comment by Quaker762** [comment]
So we should write a few API calls (like the arc file stuff) that can read n bytes of data from the loaded file (which is in a vector you pass to LoadFile) into the struct, yeah? Excuse my ignorance haha.

**Comment by z33ky** [comment]
I was thinking about dropping the `vector`. `sh3_arc_file::ReadString()` uses a `std::vector` internally because you cannot just copy bytes directly into a `std::string`. `std::string::data` does return `char*`, but it's undefined behaviour to modify that memory.
But if you look at `sh3_arc_file::ReadObject()`, you can see that eventually `gzread` will write directly to the struct's memory. I imagine the same thing for `LoadFile()`, where you will `std::ifstream::read` directly into the struct.

**Comment by Quaker762** [comment]
Alright, sounds good. It'll probably make life a lot easier being able to read into multiple types.

**Comment by Quaker762** [comment]
After doing some more testing, it seems this has been fixed. I am getting correct output from the read vector. 

I've done a bit of research, and I think the vector may be a good idea to keep. Copying from a vector will definitely come in handy when allocating buffers, because we won't have to manually probe/write a function to query the file size (though this might be a good idea to have.)

**Comment by z33ky** [comment]
Yeah, I've been thinking that this will probably load primarily dynamically-sized data. But many times there will be a fixed-sized header, so I'd imagine an interface usable as such:
```
    sh3_arc mft(...);
    sh3_arc_vfile textureFile(mft, "/path/to/texture.tex"); // vfile for "virtual file"
    texture tex;
    sh3_arc_vfile::read_error e;
    std::size_t len = textureFile.ReadObject(tex, e);
    if(e || !tex.parse_header(textureFile.length)) // parse_header checks that the header looks valid and allocates memory for tex.vec (probably textureFile.length - sizeof(texture) bytes)
    {
        //error
        return;
    }
    assert(len == sizeof(tex));
    len = textureFile.ReadData(tex.vec.data(), tex.vec.size(), e);
    if(e)
    {
        //error
        return;
    }
    assert(len == tex.vec.size());
```

Edit: This can then also be packed into a templated function, abstracting over `texture` via a `typename T`.

**Comment by z33ky** [comment]
I've thought about this some more, and this is another approach I came up with:
```
    template<typename Header> // where T is sh3_texture_header for example
    class resource
    {
        ...

        Header& header() { return reinterpret_cast<Header&>(raw.front()); }

        using iterator_range = std::pair<raw::iterator, raw::iterator>; // we could use boost::iterator_range instead
        iterator_range data() { return std::make_pair(begin(raw) + sizeof(Header), end(raw)); }

        ...

        std::vector<uint8_t> raw;
    };
```

`texture` would then just be a `resource<sh3_texture_header>`, which provides us access to the header by simply aliasing the bytes in `resource::raw` , as well as convenient access to the "body" (non-header bytes). Reading in the vector is then enough to load a resource from a file.

**Comment by Quaker762** [comment]
The only issue I see with this is that some files will most likely need to be seeked. This will be fine for none batched textures, however, most models have the texture embedded, and Heather has about 14 costumes, one main header and then _n_ headers afterwards. After this, you must seek to the correct texture itself. The same goes for map files. 

I've emailed you some code to help you understand the engine a little bit more, as someone I was in correspondence with a month ago reversed 97% of the engine, with the 3% we're going to have to do ourselves (though it should be playable with the 3% missing)

**Comment by z33ky** [comment]
In this case we can specialize `resource<sh3_model_header>` to return `begin(raw) + sizeof(Header) + header().num_sub_headers * sizeof(SubHeader)` from `data()`.
And instead of `texture` just being a `resource<sh3_texture_header>` it's a class containing one and also a `sh3_subtexture_header*` pointing into a `resource<sh3_model_header>::raw`.
Sadly C++ is not Rust which could guarantee us that this `sh3_subtexture_header` stays a valid pointer. We can either take chances, use a `shared_ptr` or make a copy of the subtexture headers.
I'd sway towards making a copy. Headers should be relatively small, so we shouldn't take a huge hit here. The `resource<sh3_model_header>` can also opt into removing the subtexture headers from `raw` if memory usage should be a concern.

I'll take a look at the files you sent me later.

**Comment by z33ky** [comment]
I've opened #95 for the generic resource loading. I think this issue can be closed then.
