### ISSUE TITLE
sub arc and arc section

### ISSUE THREAD

**Issue by z33ky** [Palm-Studios/sh3redux#46]
The documentation mentions that sub arcs (subarc and sub .arc as well) are synonymous with arc sections. There should be a single term used consistently.
I am slightly confused, but it seems that for the MFT, "section" refers to the stored information about the subarcs and the term "subarcs" refers to the actual files. In any case, I think this should be cleared up.

**Comment by Quaker762** [comment]
Sorry about that, I use them both interchangeably.

An arc section is anything that isn't arc.arc, i.e chrpl.arc.
If you look at an uncompressrd version of arc.arc, you'll see a list of files under a section, for example, chrpl. Inside these are Virtual File paths which are then converted into an index in the actual *.arc file. I refer to them as sub arcs because its sort of like a subdirectory, however, section is the more accurate term.
